# general settings
name: FDRNet
model_type: OctaveIRModel
scale: 4
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: datasets/SISR_datasets_HR_LR_x234_BIBDDN/DIV2K/DIV2K_train_HR
    dataroot_lq: datasets/SISR_datasets_HR_LR_x234_BIBDDN/DIV2K/DIV2K_train_LR_bicubic/x4
    # meta_info_file: basicsr/data/meta_info/meta_info_DIV2K800sub_GT.txt
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 12
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/SISR_datasets_HR_LR_x234_BIBDDN/Set5/HR/x4
    dataroot_lq: datasets/SISR_datasets_HR_LR_x234_BIBDDN/Set5/LR/x4
    io_backend:
      type: disk

# network structures
network_g:
  type: OctaveIRRes
  upscale: 4
  in_chans: 3
  img_size: 48
  window_size: 16
  img_range: 1.
  depths: [6,6,6,6,6,6]
  alpha: 0.334
  embed_dim: 120
  mlp_ratio: 2
  upsampler: 'pixelshuffle'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000,400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: octave
    resume_id: ~
# dist training settings
dist_params:
  backend: nccl
  port: 29500
